### ISSUE TITLE
Troubleshooting since  #22 merged

### ISSUE THREAD

**Issue by XavCC** [davidtavarez/pwndb#23]
All request return : 

```
Traceback (most recent call last):
  File "pwndb.py", line 136, in <module>
    main(emails, output)
  File "pwndb.py", line 27, in main
    print(info + " Searching for leaks...")
  File "/home/xavcc/pwndb/venv/lib/python3.6/codecs.py", line 377, in write
    self.stream.write(data)
TypeError: write() argument must be str, not bytes

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "pwndb.py", line 140, in <module>
    print(bad + " " + e)
TypeError: must be str, not TypeError
```

It seems to be related with MR #22. I've got error yesterday, update done today and then it breaks

**Comment by XavCC** [comment]
@davidtavarez It rins & works fine ;-)
